language: python
sudo: false
python:
    - 2.7
install:
    - pip install -U setuptools==33.1.1 zc.buildout==2.9.5 six==1.10.0
    - buildout bootstrap
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
